CREATE TABLE certificado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150),
    descricao TEXT,
    requer_assinatura BOOLEAN DEFAULT FALSE,
    template TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE oficina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id BIGINT,
    certificado_id BIGINT,
    titulo VARCHAR(150) NOT NULL,
    descricao TEXT,
    sala VARCHAR(50),
    data_inicio DATE,
    data_fim DATE,
    ativa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (professor_id) REFERENCES usuario(id),
    FOREIGN KEY (certificado_id) REFERENCES certificado(id)
);