CREATE TABLE matricula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    oficina_id BIGINT NOT NULL,
    data_matricula DATE DEFAULT CURRENT_DATE,
    certificado_emitido BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (aluno_id) REFERENCES aluno(id),
    FOREIGN KEY (oficina_id) REFERENCES oficina(id)
);