CREATE TABLE encontro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina_id BIGINT NOT NULL,
    data DATE,
    horario_inicio TIME,
    horario_fim TIME,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (oficina_id) REFERENCES oficina(id)
);