CREATE TABLE frequencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id BIGINT NOT NULL,
    encontro_id BIGINT NOT NULL,
    presente BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (matricula_id) REFERENCES matricula(id),
    FOREIGN KEY (encontro_id) REFERENCES encontro(id),
    UNIQUE (matricula_id, encontro_id)
);