CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    entidade VARCHAR(100),
    entidade_id BIGINT,
    acao VARCHAR(50),
    detalhes TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);