spring:
  application:
    name: ellp-oficina-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/ellp_oficina_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

server:
  port: 8080